name: PR checks

on:
  pull_request:
    branches:
      - 'main'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      firmware: ${{ steps.changes.outputs.firmware }}
      middleware: ${{ steps.changes.outputs.middleware }}
      web: ${{ steps.changes.outputs.web }}
    steps:
    - id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          firmware:
          - 'firmware/**'
          middleware:
          - 'middleware/**'
          web:
          - 'web/**'

  build-firmware:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.firmware == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: cd firmware
    - name: Install PlatformIO Core
      run: |
        curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -o get-platformio.py
        python get-platformio.py
      shell: bash
    - run: pio run
      shell: bash
  
  build-middleware:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.middleware == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: cd middleware
    - run: pip install -r requirements.txt
    - run: python test_api.py

  build-web:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.web == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - run: cd web
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build